---
database_name: "lib/image-catalog.db"
sources_name: "etc/image-sources.yaml"
template_path: "templates"
remote_repository: "git@git.pco.gadgetlab.de:cfg/image-catalog.git"
no_git_ssh_command: "git_ssh_wrapper.sh"
local_repository: "image-catalog"
branch: "main"
